### ISSUE TITLE
Dye Overhaul

### ISSUE THREAD

**Issue by Fortanono** [bigyihsuan/complicated-recipes#11]
Wood is hard to obtain, so here are my suggestions for new dye recipes.
1. White from stone, green from copper, red from iron, black from coal.
2. Smelt green to get blue dye.
3. Yellow = Green + red.
4. The mixed dyes stay the same.

```
_FROM BIGYIHSUAN_
* White, green, red, black are good
* Sure, green -> blue
* Yellow is unchanged from current
* Mixed unchanged
* Chemical plant recipes for making dyes
** Crude oil + something else?
** iron ore + water = yellow dye
** sulfur + water = yellow dye?

Bob's Compatibility:
* Use existing ores to make dye in chemical plants
* Or use wood/synthetic wood
```

**Comment by bigyihsuan** [comment]
> Yellow = Green + red.

I made these dyes thinking they were paints, so green + red != yellow. I'll find some other way to make it, though...

**Comment by Fortanono** [comment]
Maybe just add alternate recipes using oil? So you have to chop trees until you get oil processing?

**Comment by bigyihsuan** [comment]
some research says that yellow ochre is a possible real basis for yellow dye

i guess i could add alternative oil recipes

**Comment by bigyihsuan** [comment]
I've been thinking about this, it would be better to just use crude oil in a chemical plant late-game. Simpler, and less infuriating for me to code.
