### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by Byteme8bit** [bigyihsuan/complicated-recipes#26]
Failed to load mod "complicated-recipes 1.1.10"
_complicated-recipes_/data.lua:19:
....ated-creipes_/prototypes/recipes/misc-intermediates.lua:140:'}'
expected (to close'{' at line 137 near 'name'
![cr error](https://cloud.githubusercontent.com/assets/18562728/24936869/b850336c-1ee1-11e7-9dd3-2609bca6d62d.PNG)

**Comment by bigyihsuan** [comment]
ah shit. forgot a comma

**Comment by Byteme8bit** [comment]
1.1.09 works just fine haha

**Comment by Byteme8bit** [comment]
Damn you responded already, you rock!

**Comment by bigyihsuan** [comment]
release out
