### ISSUE TITLE
Circuit Network recipe expansion

### ISSUE THREAD

**Issue by bigyihsuan** [bigyihsuan/complicated-recipes#6]
- Circuit Network Connector: item for making Combinators
- CNC = Wire Acceptor, Glue (fluid), 2x LED
- Wire Acceptor = 4x Wire Bundle, Electronic Circuit
- Wire Bundle = Red Wire, Green Wire, Copper Wire, Iron Stick
- 10x Glue (fluid) = Wood, Water
- LED = Glass, Lens, Copper Wire

Changed Recipe:
- Lamp = 4x LED, 3x Iron Stick, 5x Glass

**Comment by Fortanono** [comment]
For the wires themselves you should add a dye item to choose the color, made from Oil.
