### ISSUE TITLE
Galena Ore

### ISSUE THREAD

**Issue by Fortanono** [bigyihsuan/complicated-recipes#7]
Galena would be smelted into Lead, used to make Mortars (used to crush Stone and Dyes) as well as Pipes. Silver would be an intermediate product. Make Filter Material with 2 Crushed Stone, and combine that with Galena Ore to get Silver Pebbles. Silver Plates (smelted from these Pebbles) are used in most oil-based technologies and are the gateway to mid-late game.

**Comment by bigyihsuan** [comment]
Not going to decide to add world gen or entities in this mod.

I'll find a way to get Galena from the vanilla ores, if possible.

**Comment by Fortanono** [comment]
Doesn't matter. It's just an idea I've had boiling in my head for a while. It doesn't really fit with the mod.

**Comment by bigyihsuan** [comment]
Yeah, doesn't really fit. That feels more like Bob's than a Vanilla-like addition. But I might take some ideas from it, though.
