### ISSUE TITLE
Something that actually fits this time: Make Science Packs require Glass and Dyes

### ISSUE THREAD

**Issue by Fortanono** [bigyihsuan/complicated-recipes#8]
It only seems right. Instead of making them require misc stuff from the game, make them require glass and dyes. Here would be my recipes:
- Glass Vial: 2x Glass
- SP1: Glass Vial, Red Dye
- SP2: Glass Vial, Green Dye, Electronic Circuit Board
- Transparent Plastic: Smelt Plastic
- Plastic Flask: 2x Transparent Plastic
- SP3: Plastic Flask, Blue Dye, 2x Sulfuric Acid
- Alien Pack (20): 20x Plastic Flask, 10x Purple Dye, 1x Alien Artifact

**Comment by bigyihsuan** [comment]
With the changes coming to 0.15 to the research packs, and mods already existing to put it into 0.14, there's no need.
